import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";

import QueryContext from "./(music)/common/context/QueryContext";
import NavBar from "./(music)/common/components/NavBar";
import UserProvider from "./(music)/common/context/UserProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryContext>
          <UserProvider>
            <NavBar />
            <div className="container">{children}</div>
          </UserProvider>
        </QueryContext>
      </body>
    </html>
  );
}
